[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --include=dev",
  "npm install --no-save @rolldown/binding-linux-x64-gnu@1.0.0-rc.12"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node server/dist/index.js"
