[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm ci --include=dev",
  "npm install --no-save @rolldown/binding-linux-x64-gnu@1.0.0-rc.12"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"
